### ISSUE TITLE
UI for Meetups Page

### ISSUE THREAD

**Issue by sakshi1499** [anitab-org/portal#528]
## Description
As a user,
I need a minimal, simplistic view of Meetups Page.

## Mocks
Mocks have to be created for the Meetup page.
It should include the following:
1) A search bar.
2) A location input field which should be auto filled.
3) Grid of events being organized near to that location.
4) Other events section which can include past events that were held. 

Inspiration can be taken from https://www.meetup.com/

## Acceptance Criteria
Should include all the above points.
Should follow the [Branding Guidelines](https://anitab-org.zulipchat.com/#narrow/stream/216323-design/topic/Branding.20Guidelines).

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
6 hours max.

**Comment by ritwickraj78** [comment]
The previous mockup.
![2 - Screen 2](https://user-images.githubusercontent.com/43514828/82785539-6a05f800-9e80-11ea-8bd5-0941d48bee8e.png)

**Comment by ritwickraj78** [comment]
The updated UI page
![2 - Screen 2](https://user-images.githubusercontent.com/43514828/82788158-88222700-9e85-11ea-8727-9ac9bada9400.png)

**Comment by sakshi1499** [comment]
@ritwickraj78 There is one slight change, the cards in the row have a width of x px and the cards in a column has a width of x/4 px. You have to have both equal or nearly same. I hope you get it otherwise I'll explain again :)

**Comment by ritwickraj78** [comment]
@sakshi1499 I overlooked this one. I actually tried out the square tiles and they dont look well, so I decided to go with the previous ones. If you need it square you can let me know. I will change it

**Comment by SanketDG** [comment]
Pointers:

- I would remove the location search features entirely because they will not be used by 99% of end users, hence bloat. We are not a meetup aggregator and we shouldn't aim to be one. Just a search box should be fine. If we find ourselves needing the location searches back, we can add it back.

- The "card" design primitive seems to be used both here and on the communities page, there should be a standardized set of design principles for such a component, so that they look uniform across the site.

- Instead of making the list of events as a grid, making it a vertical column display will be way more intuitive for the user. See https://www.indiehackers.com/meetups for inspiration.

**Comment by sakshi1499** [comment]
@ritwickraj78 I didn't ask you to square them, I just asked to keep the bottom and the right margin for each card to be equal

**Comment by mayburgos** [comment]
@SanketDG We already discussed this over the past few weeks. Please do not confuse Ritwick any further.

You have brought up very good points, however, as mentioned earlier we've already had weeks of meetings and back and forth discussions before the team came to a consensus. 

The whole app's design is primitive, so it's not off brand. If you would like to update the design, please create UI issues with a "Status: Available" so that this doesn't fall onto Ritwick. We can reach out to the community and design team to help re-brand the Portal Web application.

@ritwickraj78 Please stick to our original decisions. We don't have time to continue iterating mocks before the Coding Phase.

**Comment by SanketDG** [comment]
@mayburgos Absolutely, I understand. Apologies if I was implying that I want the student to absolutely do this, these were just ideas that I was bouncing off the top of my head.

Hopefully, the future mentor meetings will give me and others a better idea of the roles and responsibilities I am expected to perform.

**Comment by ritwickraj78** [comment]
@sakshi1499  Gotcha!! @SanketDG Those points are great:) Thank you for the insights. @mayburgos Sure.

**Comment by sakshi1499** [comment]
Closing UI issues, as the design team will make new issues in case required.
